DROP TABLE IF EXISTS prices;
CREATE TABLE prices (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    sourse VARCHAR(20) NOT NULL,  
    device VARCHAR(50) NOT NULL, 
    price INT(6),    
    checked TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


